In [2]:
import pandas as pd

In [5]:
torn_data_load = "1950-2021_torn.csv"

In [6]:
torn_df = pd.read_csv(torn_data_load)

In [7]:
torn_df

,om,yr,mo,dy,date,time,tz,st,stf,stn,...,len,wid,ns,sn,sg,f1,f2,f3,f4,fc
0,192,1950,10,1,1950-10-01,21:00:00,3,OK,40,23,...,15.80,10,1,1,1,25,0,0,0,0
1,193,1950,10,9,1950-10-09,02:15:00,3,NC,37,9,...,2.00,880,1,1,1,47,0,0,0,0
2,195,1950,11,20,1950-11-20,02:20:00,3,KY,21,1,...,0.10,10,1,1,1,177,0,0,0,0
3,196,1950,11,20,1950-11-20,04:00:00,3,KY,21,2,...,0.10,10,1,1,1,209,0,0,0,0
4,197,1950,11,20,1950-11-20,07:30:00,3,MS,28,14,...,2.00,37,1,1,1,101,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68863,620523,2021,9,8,2021-09-08,15:32:00,3,PA,42,0,...,0.73,30,1,1,1,109,0,0,0,0
68864,620524,2021,9,8,2021-09-08,15:35:00,3,PA,42,0,...,1.45,30,1,1,1,109,0,0,0,0
68865,620525,2021,9,8,2021-09-08,19:08:00,3,FL,12,0,...,1.45,50,1,1,1,129,0,0,0,0
68866,620526,2021,9,9,2021-09-09,02:10:00,3,CT,9,0,...,0.75,75,1,1,1,13,0,0,0,0
68867,620527,2021,9,9,2021-09-09,17:58:00,3,CA,6,0,...,1.79,9,1,1,1,37,0,0,0,0

In [8]:
torn_df.dtypes

om         int64
yr         int64
mo         int64
dy         int64
date      object
time      object
tz         int64
st        object
stf        int64
stn        int64
mag        int64
inj        int64
fat        int64
loss     float64
closs    float64
slat     float64
slon     float64
elat     float64
elon     float64
len      float64
wid        int64
ns         int64
sn         int64
sg         int64
f1         int64
f2         int64
f3         int64
f4         int64
fc         int64
dtype: object

In [9]:
torn_df['date'] = pd.to_datetime(torn_df['date'])

In [10]:
torn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68868 entries, 0 to 68867
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   om      68868 non-null  int64
 1   yr      68868 non-null  int64
 2   mo      68868 non-null  int64
 3   dy      68868 non-null  int64
 4   date    68868 non-null  datetime64[ns]
 5   time    68868 non-null  object
 6   tz      68868 non-null  int64
 7   st      68868 non-null  object
 8   stf     68868 non-null  int64
 9   stn     68868 non-null  int64
 10  mag     68868 non-null  int64
 11  inj     68868 non-null  int64
 12  fat     68868 non-null  int64
 13  loss    68868 non-null  float64
 14  closs   68868 non-null  float64
 15  slat    68868 non-null  float64
 16  slon    68868 non-null  float64
 17  elat    68868 non-null  float64
 18  elon    68868 non-null  float64
 19  len     68868 non-null  float64
 20  wid     68868 non-null  int64
 21  ns      68868 non-null  int64
 22  sn      68868 non-null  int64
 23  sg      68868 non-null  int64
 24  f1      68868 non-null  int64
 25  f2      68868 non-null  int64
 26  f3      68868 non-null  int64
 27  f4      68868 non-null  int64
 28  fc      68868 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(19), object(2)
memory usage: 15.2+ MB

In [11]:
# Export ETL data
torn_df.to_csv("all_tornadoes1950-2021.csv", index=False)

In [19]:
from sqlalchemy import create_engine
torn_df = pd.read_csv('https://raw.githubusercontent.com/Rolosaregood/Tornados/Gavin_Project3/all_tornadoes1950-2021.csv')
engine = create_engine('sqlite:///my_database.db', echo=False)
torn_df.to_sql('group6_Tornadoes', con=engine)

HTTPError: HTTP Error 404: Not Found

In [16]:
result = engine.execute('PRAGMA table_info(group6_Tornadoes)').fetchall()
for row in result:
    print(row)

(0, 'index', 'BIGINT', 0, None, 0)
(1, 'om', 'BIGINT', 0, None, 0)
(2, 'yr', 'BIGINT', 0, None, 0)
(3, 'mo', 'BIGINT', 0, None, 0)
(4, 'dy', 'BIGINT', 0, None, 0)
(5, 'date', 'DATETIME', 0, None, 0)
(6, 'time', 'TEXT', 0, None, 0)
(7, 'tz', 'BIGINT', 0, None, 0)
(8, 'st', 'TEXT', 0, None, 0)
(9, 'stf', 'BIGINT', 0, None, 0)
(10, 'stn', 'BIGINT', 0, None, 0)
(11, 'mag', 'BIGINT', 0, None, 0)
(12, 'inj', 'BIGINT', 0, None, 0)
(13, 'fat', 'BIGINT', 0, None, 0)
(14, 'loss', 'FLOAT', 0, None, 0)
(15, 'closs', 'FLOAT', 0, None, 0)
(16, 'slat', 'FLOAT', 0, None, 0)
(17, 'slon', 'FLOAT', 0, None, 0)
(18, 'elat', 'FLOAT', 0, None, 0)
(19, 'elon', 'FLOAT', 0, None, 0)
(20, 'len', 'FLOAT', 0, None, 0)
(21, 'wid', 'BIGINT', 0, None, 0)
(22, 'ns', 'BIGINT', 0, None, 0)
(23, 'sn', 'BIGINT', 0, None, 0)
(24, 'sg', 'BIGINT', 0, None, 0)
(25, 'f1', 'BIGINT', 0, None, 0)
(26, 'f2', 'BIGINT', 0, None, 0)
(27, 'f3', 'BIGINT', 0, None, 0)
(28, 'f4', 'BIGINT', 0, None, 0)
(29, 'fc', 'BIGINT', 0, None, 0)